language: node_js

node_js:
  - '6.9.2'

branches:
  only:
  - /^master$/

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm run bower -- install

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov --file coverage/lcov.info --disable search
